language: android
jdk:
  - oraclejdk8

branches:
  except:
    - /^v[0-9]/

android:

  licenses:
    - android-sdk-license-.+
    - '.+'

  components:
    # Uncomment lines below whether you want
    # to use the latest version of Android SDK Tools.
    - platform-tools
    - tools

    # The version of the Build Tools used for your project.
    - build-tools-23.0.3

    # The version of the SDK Android used to compile your project.
    - android-23

    # Additional components.
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-19

    # Specify, at least, one system image
    # whether you need to run the emulator during your tests.
    - sys-img-armeabi-v7a-android-19
    - sys-img-x86-android-17

before_install:
    - chmod +x gradlew
    # Accepting SDK licenses.
    - mkdir "$ANDROID_HOME/licenses" || true
    - echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
    - echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"

script:
    ./gradlew clean assembleRelease publishApkRelease